### ISSUE TITLE
[Discussão] Layout

### ISSUE THREAD

**Issue by nandomoreirame** [php-pr/layout-site#1]
Primeiramente gostaria de dizer que o front-end será feito com o [Bootstrap 3](http://getbootstrap.com/) que não podemos sair muito dos estilos aplicados nos [componentes](http://getbootstrap.com/components/) do mesmo.

Eu sugiro que não fique muito puxado para um site de designers e afins e sim um para programadores, ou seja sem muitas cores (colorido demais) ou muitos vetores etc... vamos focar na simplicidade e apresentação do conteúdo para o usuário final.

Podemos pegar o novo site do [PHP.net](http://www.php.net/) como exemplo, é limpo, apresenta o conteúdo para o usuário de forma clara e legível, e não deixa de ser lindo <3

No mais seria isso, fico no aguardo de alguma sugestão para começar a desenhar o Layout em si.

Grato.

**Comment by andrebian** [comment]
Galera, vamos agitar nossa discussão sobre layout novamente?

@jeanmalves, vc me enviou dias atrás uma prévia do layout, quer colocar aqui pro pessoal discutir/opiniar?

**Comment by joridos** [comment]
Legal galera, bora movimentar a ideia novamente.

**Comment by andrebian** [comment]
@joridos (y)

**Comment by jeanmalves** [comment]
Galera, segue a prévia do layout que desenvolvi baseado na wireframe que já tinhamos discutido.
Podem opinar a vontade rss
![layout_phppr-1](https://cloud.githubusercontent.com/assets/2343666/10317624/c8c7d7ae-6c3b-11e5-9b52-60386b442898.jpg)

**Comment by andrebian** [comment]
Se a seção de oportunidades cair dava pra colocar os eventos pra cima e logo abaixo uma seção com hangouts, e daí é claro, a gente fazer hangouts. Chamar devs de vários cantos do estado, sei lá tipo um hangout por mês...

**Comment by joridos** [comment]
boa ideia.

**Comment by jeanmalves** [comment]
Legal.

**Comment by flaviosilveira** [comment]
@jeanmalves Tem esse Layout ai?
Vamos fazer o HTML e colocar para rodar?

**Comment by jeanmalves** [comment]
Flávio, já está codificado o layout, o HTML e CSS estão prontos. Da pra
criar um repositório no github da comunidade php-pr e subir la. Ou como preferir.

Em 14/12/2016 23:41, "Flávio Augusto da Silveira" <notifications@github.com>
escreveu:

**Comment by flaviosilveira** [comment]
Show!
Pode criar esse repositório? Aí dou continuidade aqui.

**Comment by jeanmalves** [comment]
Blz to mexendo aqui já.

Em 14/12/2016 23:49, "Flávio Augusto da Silveira" <notifications@github.com>
escreveu:

**Comment by jeanmalves** [comment]
@flaviosilveira já está criado o repositório com os arquivos. Se precisar modificar algumas coisas ou estiver alguma coisa fora do lugar fique a vontade para contribuir.

https://github.com/php-pr/site

**Comment by flaviosilveira** [comment]
@jeanmalves Valeu cara!
Vamos fazer essa parada rodar.

Vamos falando.

**Comment by jeanmalves** [comment]
Pode crer!  Vamo ae!

**Comment by juniorth6** [comment]
Galera se precisar de ajuda conta comigo ai. Abração.

**Comment by nandomoreirame** [comment]
Vamo ae galera! :rocket:

**Comment by nandomoreirame** [comment]
@jeanmalves vc usou algum task runner e algum pré-processador pra gerar os arquivos estáticos?

**Comment by nandomoreirame** [comment]
@jeanmalves Seria bom usarmos o Bower pra gerenciar as dependencias externas do projeto, jquery, bootstrap, etc...

**Comment by jeanmalves** [comment]
Não usei nada, apenas codifiquei para ter um html definido as dependências.
Pode usar o bower sim, fique a vontade. Pode ate usar algum framework se
preferir.

Em 15/12/2016 17:25, "Fernando Moreira" <notifications@github.com> escreveu:

**Comment by nandomoreirame** [comment]
Show! Vou fazer algumas coisas nesse fim de semana e mandar um PR pra vocês
analisarem 👍

**Comment by jeanmalves** [comment]
Blz!

Em 15/12/2016 19:43, "Fernando Moreira" <notifications@github.com> escreveu:
