### ISSUE TITLE
Discussão para escolher o processo de desenvolvimento

### ISSUE THREAD

**Issue by joridos** [php-pr/layout-site#6]
Conforme a dica do @jeanmalves, abri essa issue para conversarmos sobre o processo de desenvolvimento, que atualmente é:
- [definir o que terá no site:
  (Menus, formato site (blog ou não), sessões (artigos, noticias, empregos,e tc), enfim que tipo de informação iremos passar).](https://github.com/php-pr/layout-site/issues/2)
- Esquema Wireframe do site.
- Criação Protótipo.
- Definir as ferramentas para o desenvolvimento.
- Execução do projeto.
- Entrega final.

Na minha opinião acho que nós estagnamos na parte: **Esquema Wireframe do site**.

Qual a sugestão de vocês? @andrebian, @nandomoreiraweb, @juniorth6, @felipecwb, @paulomartinhago, @brunoew, @luuckx2

**Comment by jeanmalves** [comment]
Precisamos criar um documento deixando claro o que terá no site conforme já
discutimos para concluirmos o segundo item.

Em 23 de janeiro de 2015 13:17, Jonatan Ribeiro dos Santos <
notifications@github.com> escreveu:

**Comment by joridos** [comment]
@jeanmalves [nós já temos aqui](https://github.com/php-pr/layout-site/tree/master/funcionalidades/propostas), só precisa a galera votar e escolhermos.

**Comment by jeanmalves** [comment]
ok, artigos e noticias vai ter também?

Em 23 de janeiro de 2015 13:26, Jonatan Ribeiro dos Santos <
notifications@github.com> escreveu:

**Comment by joridos** [comment]
Acho que sim @jeanmalves,  vai ser algo como o [Tableless](http://tableless.com.br/), onde quem quiser postar vai passar por um triagem, e vai poder fazer posts para o blog, e também vai ter noticias creio eu.

**Comment by felipecwb** [comment]
@jeanmalves, vejo que artigos e noticias são meio que uma obrigatoriedade. 
Porque todos nós temos algo a compartilhar. Inclusive quem está lendo.

Muito boa a questão @joridos. 
Liberar uma página pra galera postar e verificar se o post vai entrar no site ou não.

**Comment by andrebian** [comment]
Boa @felipecwb tipo os próprios visitantes serem moderadores. Assim quando o post atingir um número X de approves ele vai ao ar oficialmente. Joga isso nas [funcionalidades](https://github.com/php-pr/layout-site/tree/master/funcionalidades/propostas) Felipe.

**Comment by andrebian** [comment]
Ainda, quando não atingir o total esperado mas estiver muito próximo e se passar uma semana de sua postagem por exemplo.

**Comment by felipecwb** [comment]
Agora to meio sem tempo. Mas assim que der eu coloco lá.

**Comment by joridos** [comment]
Show de bola a ideia @felipecwb

**Comment by kleberksms** [comment]
Então, acho que pode se interessante ter um área de vídeos tutoriais, tem gente que prefere gravar a escrever

**Comment by felipecwb** [comment]
:+1: 
coloquem no youtube e nós adcionamos

**Comment by jeanmalves** [comment]
Estou fazendo a wireframe do layout, em breve postarei.
Em 26/01/2015 10:49, "Felipe Francisco" <notifications@github.com> escreveu:

**Comment by joridos** [comment]
:+1:

**Comment by jeanmalves** [comment]
Acabei de terminar a wireframe, deixe suas considerações por favor.



2015-01-26 22:11 GMT-02:00 Jonatan Ribeiro dos Santos <
notifications@github.com>:

**Comment by andrebian** [comment]
O @jeanmalves enviou por email o wireframe, segue em anexo por aqui também pra vcs verem.

![wireframe_phppr](https://cloud.githubusercontent.com/assets/2091739/5938682/93db9b92-a6e4-11e4-8c66-5346911f555d.gif)

**Comment by paulomartinhago** [comment]
Achei interessante a ideia das oportunidades e eventos na direita, ficou bem focado. Uma coisa que talvez ficasse legal, é colocar o próximo evento no topo do site, dando um destaque. Um campo de busca também seria interessante no topo.

Acho que poderíamos também adicionar o likebox do PHPPR no rodapé.

**Comment by jeanmalves** [comment]
Oi Paulo, legal suas observações. Hoje analisando melhor vi que o campo de
busca é importante.
Quanto ao destaque, acho que não ficou muito claro mas após o menu, a
imagem grande com uma chamada do lado não é especificamente para noticias
mas também para algo importante,acho que é preciso colocar o titulo do
bloco chamado de Destaque.

Em 28 de janeiro de 2015 12:11, Paulo Martinhago <notifications@github.com>
escreveu:

**Comment by andrebian** [comment]
Eu acho que o que o @paulomartinhago quis dizer é colocar um banner divulgando sempre o(s) evento(s) mais próximo(s) de acontecer(em).

**Comment by andrebian** [comment]
Bem eu acho que a aprovação do wireframe e sugestões poderiam ir para uma isseu específica. Aí por aqui mantemos a discussão com relação ao restante do processo:

 - Ferramentas para desenvolvimento
 - code base utilizado (particularmente acho que seria interessante ,já que estamos no meio de desenvolvedores que façamos do zero com base em algum framework, não utilizar o Wordpress)
  

E mais detalhes que possam surgir.

De imediato o que seria o ideal é que o pessoal comece também a votar nas funcionalidades: https://github.com/php-pr/layout-site/tree/master/funcionalidades/propostas. Quem quiser comentar sobre qualquer uma das funcionalidades sinta-se a vontade para abrir uma issue fazendo referência à funcionalidade. Em aprovada somente vão ficar após a maioria dos envolvidos concordarem e as definições forem lapidadas.

**Comment by felipecwb** [comment]
:+1: wireframe @jeanmalves muito bom. simples e objetivo.
:+1: desenvolver do zero. Algo como esse projeto [PHPSC/phpsc-conf](https://github.com/PHPSC/phpsc-conf)
> _Eu não curo muito a ideia de usar um framework por completo. Podemos juntar as necessidades com composer_

**ferramentas que precisamos (acho kk):**
- Rotas.
- Container
- DB (Doctrine simples e muito utilizado)
- Twig (Para simplificar a parte do layout)
- PHPUnit (Temos que ter testes)
- Travis CI.
- etc...

**Comment by andrebian** [comment]
E o mais legal de tudo, será um trabalho em equipe, reunindo pessoas de vários locais, alguns inclusive concorrentes diretos para criar a melhor solução possível. Vai ser massa!

**Comment by jeanmalves** [comment]
Tem algumas ferramentas q ainda não tive oportunidade de usar, será um
grande aprendizado.
Em 28/01/2015 15:27, "Andre Cardoso" <notifications@github.com> escreveu:

**Comment by felipecwb** [comment]
Eu gostaria muito de usar [SOFEA](http://pt.slideshare.net/zigolis/sofea-arquiteturas-rest-com-backbone-html5-by-gabriel-zigolis) :) onde temos um server-side totalmente separado do client-side, e que se comunicam via API REST.

Mas não é bom por causa de SEO e mais.

**Comment by brunoew** [comment]
O que acham de usar um Micro Framework, tipo Silex ou Slim? O Silex é
baseado em componentes do Symphony 2 e muito fácil de usar e manter:
http://silex.sensiolabs.org/

Em Wed Jan 28 2015 at 15:33:00, JEAM MARTINS ALVES <notifications@github.com>
escreveu:

**Comment by luuckx2** [comment]
Eu apoio usar o CakePHP =D

**Comment by felipecwb** [comment]
não vamos ter uma guerra de frameworks, por favor.

**Comment by kleberksms** [comment]
Sério isso?
Acho que poderíamos ser práticos, o que resolve o nosso problema de forma mais rápida?
Sinceramente, não vejo a necessidade de frameworks e etc... acho que um wordpress resolve o problema.

**Comment by andrebian** [comment]
é, tem de ser algo que todos consigam acompanhar, um zend pode ser bom para alguns mas difícil para outros, bem como outro framework teremos o mesmo problema... será uma boa discussão, e espero que permaneça sadia.

A questão do SEO precisamos prezar nos seguintes pontos:

 - Artigos
 - Eventos
 - Notícias
 - Vagas de emprego

estes conteúdos DEVEM receber um cuidado muito mais que especial pois geralmente é o conteúdo em geral que atrai visitantes.

**Comment by brunoew** [comment]
Não seria uma guerra de frameworks, mas uma ideia do que poderia ser usado
como controle de rotas, exposição de API, etc... Se não aceitam a sugestão
basta dizer como o Kleber e André comentaram ai... Dá uma alternativa e seu
ponto de vista e pronto! Só opinei pois pensei que o intuito era a troca de
ideias e conhecimento.

Em Wed Jan 28 2015 at 15:52:21, Felipe Francisco <notifications@github.com>
escreveu:

**Comment by andrebian** [comment]
@kleberksms a intenção seria para que um grupo de desenvolvedores criem sua solução, será uma experiência positiva para todos. 90% ou mais dos envolvidos são programadores e seria bom deixar a imaginação fluir. Confesso que pensei no Wordpress mas ele pode nos limitar para algo mais complexo.

Sugeri isso por uma questão de aprendizado para todos os programadores afinal de contas muitos trabalharemos com coisa que sequer vimos antes, não acha interessante?

**Comment by andrebian** [comment]
Mas assim, isso é pra gerar discussão, se a maioria acreditar que é melhor fazer em WorPress por já ter uma porrada de coisa pronta, sem problemas, espero que ninguém fique sentido se a sua opinião não seguir a da maioria.

**Comment by kleberksms** [comment]
@andrebian se for pelo esforço de aprender algo "novo", prefiro o seguinte:
vamos fazer sem frameworks full stack, vamos usar N micro e juntar tudo pelo composer, acho que a nível de aprendizado, é  ainda fazemos a camada de visualização com js, levando em consideração APIs e camadas separadas, assim acho que o aprendizado iria subir para todos, mas ai o #foco não é o site do php-pr em si, e as informações que serão disponibilizadas, mas o conjunto do todo, e se for isso, temos que abrir milestones no git, e issues, para conseguirmos ter um MVP

**Comment by andrebian** [comment]
@kleberksms não posso deixar de lhe dar razão, realmente desta forma (escolhendo N ferramentas) estaremos perdendo o foco em ter o produto final que é "o site do PHP PR".

**Comment by jeanmalves** [comment]
Eu vejo assim, se o intuito é expandir muito acho melhor usar ferramentas
desacopladas e não usar wordpress, se for só pra manter podemos usar o
WordPress exceto se decidirmos criar nosso projeto do zero por questão de
experiência.

Como não é pra nenhum cliente específico eu prefiro criar do zero.
Em 28/01/2015 16:06, "Andre Cardoso" <notifications@github.com> escreveu:

**Comment by andrebian** [comment]
Essa foi a intenção de eu tocar no assunto, cada um expor suas ideias e seus argumentos. Aparentemente tá fluindo bem.

**Comment by kleberksms** [comment]
O que vocês acham:
Criamos o site do php-pr em wordpress, para conseguirmos alcançar o objetivo;

e para "incentivo" ao desenvolvimento e crescimento de todos da comunidade, fazemos um "wordpress" do nosso jeito.
Assim podemos criar algo que de fato seja legal para todos, e empolgue todos.

Sabemos que um site em wordpress em 3 dias depois de um layot pronto já esta no ar.

proposta, o que acham?

**Comment by brunoew** [comment]
Eu concordo com o argumento do @kleberksms <https://github.com/kleberksms> e
por essa razão sugeri um MICRO framework no comentário anterior. Acho que
seria uma excelente forma de todos contribuírem. Não vejo como uma sugestão
de usar ferramenta X ou Y possa ser uma guerra de frameworks, são apenas
opiniões.

Em Wed Jan 28 2015 at 16:12:44, Andre Cardoso <notifications@github.com>
escreveu:

**Comment by kleberksms** [comment]
a ideia o "wordpress" do nosso jeito é um exemplo, não necessariamente deve ser um cms, mas qualquer outra coisa que todo queiramos

**Comment by jeanmalves** [comment]
Eu estou criando temas personalizados no WordPress, se mais alguém estiver
da pra juntar as forças caso for decidido WordPress.
Em 28/01/2015 16:16, "Andre Cardoso" <notifications@github.com> escreveu:

**Comment by andrebian** [comment]
Este eu acho que vale um questionário...

Opções:

 - Wordrepss
 - Cake
 - Zend
 - Slim
 - Amarrados com composer (Silex, Doctrine...)
 
Se alguém mais tiver opções que não listei comenta aí que hoje a noite eu crio um form no google docs pra gente votar ;)

**Comment by jeanmalves** [comment]
Apoio essa idéia. Projeto para todos contribuirem.
Em 28/01/2015 16:18, "Kleber Syd Moraes da Silva" <notifications@github.com>
escreveu:

**Comment by kleberksms** [comment]
@andrebian 

acho que a pergunta certa seria:

Wordpress x Outros

**Comment by felipecwb** [comment]
Gosto de que seja projeto do zero.
Criar o repo e as miletones para o produto final. 
As ferramentas podem ser discutidas e inseridas atraves de issues que vão sendo criadas para a construção do produto.

@kleberksms fico com outros

**Comment by kleberksms** [comment]
vamos contabilizar por aqui mesmo

**Comment by andrebian** [comment]
Acho que tudo vai do que queremos agora. Se queremos o novo site no ar logo, o ideal seria optar por algo rápido, se a intenção é "curtir o caminho" ao invés de simplesmente chegar ao destino seria melhor outras ferramentas conforme sugeriram também. 

Apenas para refletirem, o que temos hoje é ISSO: http://www.phppr.net/

**Comment by kleberksms** [comment]
http://phpsp.org.br/wp-login.php?redirect_to=http%3A%2F%2Fphpsp.org.br%2FWP-ADMIN%2F&reauth=1

**Comment by felipecwb** [comment]
@brunoew peço desculpas pelo "Não vamos fazer guerra de frameworks." acho que me expressei mal. To tão acostumados com brigas nas comunidades que não dei atenção a opnião. sorry

**Comment by jeanmalves** [comment]
Eu voto no Wordpress.

**Comment by kleberksms** [comment]
Acho que tenho a solução:

Os dois, criamos ao mesmo tempo dois projetos separados, 
dividimos em dois times, é um fato que o time WP vai terminar antes, mas vai ter uma resposta rápida para o problema, nisto o time dois, vai começar com a arquitetura, criamos as milestones e as issues
e vamos fazendo a sprint, uma a uma

**Comment by andrebian** [comment]
Ficou com vergonha de ver o atual né? ha ha ha

**Comment by felipecwb** [comment]
@andrebian kkk bem precisa de uma reforma.

**Comment by kleberksms** [comment]
o que acha:

time 1:
@andrebian conduz a equipe

time 2:
@jeanmalves conduz a equipe


o time 1 é uma arquitetura geral, ai escolhes quais ferramentas vamos usar

o time 2 faz o wp, com todas as features que utilizaremos (as que realmente precisam)

após a conclusão do time 2, ele entra na próxima sprint do time 1

**Comment by andrebian** [comment]
Certeza @felipecwb , e conteúdo também... os acessos tão bem poucos...

![acessos](https://cloud.githubusercontent.com/assets/2091739/5944052/217ddaac-a70b-11e4-9268-b7ea459e0726.png)

**Comment by brunoew** [comment]
Sem problemas @felipecwb. 
Eu voto no WordPress para atingir o objetivo, apesar de achar que a construção do zero seria mais interessante e gerar mais discussões (boas).

**Comment by kleberksms** [comment]
@brunoew , por isso falo de fazer os dois

**Comment by andrebian** [comment]
@brunoew aí entra a sugestão do @kleberksms, um time foca em ter algo apresentável para muito breve e outro foca em fazer algo mais elaborado.

**Comment by andrebian** [comment]
Aí cada um escolhe em qual time quer trabalhar. Assim, de cara prefiro fazer parte da entrega rápida pois estou com pouco tempo hábil.

**Comment by brunoew** [comment]
Legal, então estou com o @kleberksms

**Comment by kleberksms** [comment]
ai podemos começar na primeira ou segunda semana de fevereiro, definimos quem vai ser o PO e Scrum Master, definimos os sprint por milestones e issues por tasks, e nos commits, favor fechar a issue

**Comment by andrebian** [comment]
Todos de acordo com um time para entregar um produto rápido e outro para criar coisas mais elaboradas? Quem concorda dá um joinha aí.

:+1:

**Comment by kleberksms** [comment]
:+1:

**Comment by felipecwb** [comment]
:+1:

**Comment by brunoew** [comment]
:+1:

**Comment by andrebian** [comment]
:+1:

**Comment by andrebian** [comment]
quem não concorda dá um joinha invertido (  :-1:  )

**Comment by jeanmalves** [comment]
(y)

**Comment by jeanmalves** [comment]
chi kkkk como dar joinha aqui rss?.

**Comment by jeanmalves** [comment]
:+1:

**Comment by jeanmalves** [comment]
aeeeeee hahahahha

**Comment by andrebian** [comment]
@joridos @luuckx2 @paulomartinhago o que vcs acham sobre isso ( https://github.com/php-pr/layout-site/issues/6#issuecomment-71889443 )?

**Comment by kleberksms** [comment]
https://github.com/php-pr/site-wordpress/issues

**Comment by andrebian** [comment]
tem coisas que com certeza serão comuns tanto para  versão WP quanto para o novo. Um exemplo, é a integração com os eventos do MeetUp. Aí dá pra bolar um pequeno módulo destas reaproveitáveis fazendo com que fique fácil portar de um lado para o outro.

**Comment by joridos** [comment]
@andrebian, estou viajando mas achei que agora tomamos um rumo ahhahaha, por min ta top demais cara, vamos que vamos, eu vou ajudar tanto em um quanto em outro, estamos ai para tudo...

**Comment by andrebian** [comment]
Perfeito, como tivemos a maioria apoiando então será um projeto pra substituir a coisa feia que tá no ar hoje (http://phppr.net) e outro, a versão 2.0 startando quase que imediatamente com recursos mais bem elaborados.

**Comment by andrebian** [comment]
E o layout? será o mesmo em ambas as versões correto?

**Comment by brunoew** [comment]
Sim, mesmo layout

**Comment by andrebian** [comment]
:+1:

**Comment by andrebian** [comment]
Beleza, então vamos correr pra definir o layout logo. Bem o wireframe que o @jeanmalves disponibilizou tá bem legal, dá pra amadurecermos ele e em seguida ver alguém que possa colaborar criando a identidade visual de cores.

**Comment by juniorth6** [comment]
Galera me prontifico em ajudar na criação da identidade visual de cores.
Abração



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=juniorth6@gmail.com&idSignature=22>

Em 28 de janeiro de 2015 17:33, Andre Cardoso <notifications@github.com>
escreveu:

> Beleza, então vamos correr pra definir o layout logo. Bem o wireframe que
> o @jeanmalves <https://github.com/jeanmalves> disponibilizou tá bem
> legal, dá pra amadurecermos ele e em seguida ver alguém que possa colaborar
> criando a identidade visual de cores.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/php-pr/layout-site/issues/6#issuecomment-71899658>.
>



--

**Comment by brunoew** [comment]
ótimo!

**Comment by andrebian** [comment]
Boa @juniorth6 :+1:

**Comment by juniorth6** [comment]
Até ajudo tambem no front mais nao posso ficar com muita coisa porque estou
em precesso de mudança de pais, ai já viu o caos intalado kkk.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=juniorth6@gmail.com&idSignature=22>

2015-01-28 17:38 GMT-02:00 Andre Cardoso <notifications@github.com>:

> Boa @juniorth6 <https://github.com/juniorth6> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/php-pr/layout-site/issues/6#issuecomment-71900578>.
>



--

**Comment by paulomartinhago** [comment]
@andrebian :+1:

**Comment by jeanmalves** [comment]
Ajudo na criação também, tenho experiência com criação de layouts. Uma sugestão, primeiramente precisamos fazer um protótipo do layout com as cores, imagens etc para fazermos as mudanças finais para depois codificá-lo.

**Comment by flaviosilveira** [comment]
Pessoal,
Vamos seguir no que foi decidido aqui?

Fazer uma primeira versão em Wordpress, começar a rodar.
E depois começar um desenvolvimento do zero.

É isso?
Posso abrir as issues para fazermos a primeira versão em Wordpress?

**Comment by jeanmalves** [comment]
OK, concordo. :+1:

**Comment by andrebian** [comment]
Estou de acordo.

**Comment by nandomoreirame** [comment]
De acordo, vamo que vamo!
