### ISSUE TITLE
Funcionalidade [Eventos]

### ISSUE THREAD

**Issue by andrebian** [php-pr/layout-site#9]
Referência: https://github.com/php-pr/layout-site/blob/master/funcionalidades/propostas/Eventos.md

Em minha opinião, passamos diretamente pra seção de aprovadas, o que acham?

**Comment by felipecwb** [comment]
:+1:

**Comment by andrebian** [comment]
Pessoal quem aprova esta funcionalidade manda um joinha aí, estamos em 8 usuários, 50% +1 é aprovada.

Bora lá

@jeanmalves
@joridos
@nandomoreirame
@kleberksms
@fatorx
@paulomartinhago

**Comment by andrebian** [comment]
:+1:

**Comment by joridos** [comment]
:+1:

**Comment by nandomoreirame** [comment]
+1

**Comment by andrebian** [comment]
@jeanmalves
@fatorx 
@paulomartinhago
@kleberksms 

Apenas um voto de algum de vcs manda a funcionalidade "Eventos" de proposta para aceita... O que nos dizem?

**Comment by jeanmalves** [comment]
Eventos aceito.

Em 6 de outubro de 2015 14:10, Andre Cardoso <notifications@github.com>
escreveu:

**Comment by andrebian** [comment]
Perfeito, a maioria dos envolvidos optou por termos uma seção de eventos, encerro esta issue.

@nandomoreirame vc que manja dos paranaue de milestones, se eu fechar esta issue o que ocorre? Se preferir eu deixo a issue aberta.

**Comment by nandomoreirame** [comment]
Pode fechar @andrebian ... todo histórico permanece ;)

**Comment by andrebian** [comment]
perfeito, valeu!
